name: kinora_flow
description: "Kinora Flow Event Driven State Management"
version: 1.0.0
homepage: https://github.com/kinora-app-br/kinora_flow
issue_tracker: https://github.com/kinora-app-br/kinora_flow/issues
documentation: https://github.com/kinora-app-br/kinora_flow/blob/main/README.md
repository: https://github.com/kinora-app-br/kinora_flow

topics:
  - state-management
  - event-driven

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
